name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
    - cron: 10 10 * * *
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pre-commit'
        uses: dycw/action-pre-commit@latest
        with:
          repos: |-
            dycw/conformalize
            pre-commit/pre-commit-hooks
          token-checkout: ${{secrets.GITHUB_TOKEN}}
          token-uv: ${{secrets.GITHUB_TOKEN}}
      - if: github.event_name == 'pull_request'
        name: Run 'pre-commit' hooks
        uses: dycw/action-run-hooks@latest
        with:
          repos: |-
            pre-commit/pre-commit-hooks
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pyright'
        uses: dycw/action-pyright@latest
        with:
          python-version: "3.12"
          token-checkout: ${{secrets.GITHUB_TOKEN}}
          token-uv: ${{secrets.GITHUB_TOKEN}}
      - name: Run 'pyright'
        uses: dycw/action-pyright@latest
        with:
          python-version: "3.12"
  pytest:
    env:
      CI: "1"
    name: pytest (${{matrix.os}}, ${{matrix.python-version}},
      ${{matrix.resolution}})
    runs-on: ${{matrix.os}}
    steps:
      - name: Run 'pytest'
        uses: dycw/action-pytest@latest
        with:
          python-version: ${{matrix.python-version}}
          resolution: ${{matrix.resolution}}
          token-checkout: ${{secrets.GITHUB_TOKEN}}
          token-uv: ${{secrets.GITHUB_TOKEN}}
      - name: Run 'pytest'
        uses: dycw/action-pytest@latest
        with:
          python-version: ${{matrix.python-version}}
          resolution: ${{matrix.resolution}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
        resolution:
          - highest
          - lowest-direct
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'ruff'
        uses: dycw/action-ruff@latest
        with:
          token-checkout: ${{secrets.GITHUB_TOKEN}}
          token-ruff: ${{secrets.GITHUB_TOKEN}}
      - name: Run 'ruff'
        uses: dycw/action-ruff@latest
